/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EmailRouteImport } from './routes/email'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileAboutRouteImport } from './routes/profile.about'
import { Route as ProfileCertificatesRouteImport } from './routes/profile.certificates'
import { Route as ProfileContactRouteImport } from './routes/profile.contact'
import { Route as ProfileEducationRouteImport } from './routes/profile.education'
import { Route as ProfileSkillsRouteImport } from './routes/profile.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAboutRoute = ProfileAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileCertificatesRoute = ProfileCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileContactRoute = ProfileContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEducationRoute = ProfileEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSkillsRoute = ProfileSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/research': typeof ResearchRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/certificates': typeof ProfileCertificatesRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/education': typeof ProfileEducationRoute
  '/profile/skills': typeof ProfileSkillsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/certificates': typeof ProfileCertificatesRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/education': typeof ProfileEducationRoute
  '/profile/skills': typeof ProfileSkillsRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/research': typeof ResearchRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/certificates': typeof ProfileCertificatesRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/education': typeof ProfileEducationRoute
  '/profile/skills': typeof ProfileSkillsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/profile'
    | '/research'
    | '/profile/about'
    | '/profile/certificates'
    | '/profile/contact'
    | '/profile/education'
    | '/profile/skills'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/profile/about'
    | '/profile/certificates'
    | '/profile/contact'
    | '/profile/education'
    | '/profile/skills'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/profile'
    | '/research'
    | '/profile/about'
    | '/profile/certificates'
    | '/profile/contact'
    | '/profile/education'
    | '/profile/skills'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmailRoute: typeof EmailRoute
  MeetingsRoute: typeof MeetingsRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/about': {
      id: '/profile/about'
      path: '/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof ProfileAboutRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/certificates': {
      id: '/profile/certificates'
      path: '/certificates'
      fullPath: '/profile/certificates'
      preLoaderRoute: typeof ProfileCertificatesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/contact': {
      id: '/profile/contact'
      path: '/contact'
      fullPath: '/profile/contact'
      preLoaderRoute: typeof ProfileContactRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/education': {
      id: '/profile/education'
      path: '/education'
      fullPath: '/profile/education'
      preLoaderRoute: typeof ProfileEducationRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/skills': {
      id: '/profile/skills'
      path: '/skills'
      fullPath: '/profile/skills'
      preLoaderRoute: typeof ProfileSkillsRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileAboutRoute: typeof ProfileAboutRoute
  ProfileCertificatesRoute: typeof ProfileCertificatesRoute
  ProfileContactRoute: typeof ProfileContactRoute
  ProfileEducationRoute: typeof ProfileEducationRoute
  ProfileSkillsRoute: typeof ProfileSkillsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAboutRoute: ProfileAboutRoute,
  ProfileCertificatesRoute: ProfileCertificatesRoute,
  ProfileContactRoute: ProfileContactRoute,
  ProfileEducationRoute: ProfileEducationRoute,
  ProfileSkillsRoute: ProfileSkillsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmailRoute: EmailRoute,
  MeetingsRoute: MeetingsRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
